# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 187213f11fce1af60a2f5195178df6ddc09dfc240303c00ea19735c61e6e613c644a912224ac2db933aaf4b0496ac861ac8c2b8775b5cec8c429e4e0ab92d302

test:
  secret_key_base: d04f6f69e1bc5a776eb769eac28ec2dc026aac0ffc668ab7af2a0006eb98cbbe1843bec2ac945ac47415bfacf4dd2b3c27f7c9fbfa12f9eb11a793c416903212

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
